USE QLSVNhom;
GO

IF OBJECT_ID(N'dbo.BANGDIEM', N'U') IS NOT NULL DROP TABLE dbo.BANGDIEM;
IF OBJECT_ID(N'dbo.SINHVIEN', N'U') IS NOT NULL DROP TABLE dbo.SINHVIEN;
IF OBJECT_ID(N'dbo.HOCPHAN', N'U') IS NOT NULL DROP TABLE dbo.HOCPHAN;
IF OBJECT_ID(N'dbo.LOP', N'U') IS NOT NULL DROP TABLE dbo.LOP;
IF OBJECT_ID(N'dbo.NHANVIEN', N'U') IS NOT NULL DROP TABLE dbo.NHANVIEN;
GO

CREATE TABLE dbo.NHANVIEN
(
    MANV     VARCHAR(20)     NOT NULL,
    HOTEN    NVARCHAR(100)   NOT NULL,
    EMAIL    VARCHAR(20)     NULL,
    LUONG    VARBINARY(MAX)  NULL,
    TENDN    NVARCHAR(100)   NOT NULL,
    MATKHAU  VARBINARY(32)   NOT NULL, /* SHA2_256 */
    PUBKEY   VARCHAR(20)     NULL,

    CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV),
    CONSTRAINT UQ_NHANVIEN_TENDN UNIQUE (TENDN)
);
GO

CREATE TABLE dbo.LOP
(
    MALOP    VARCHAR(20)     NOT NULL,
    TENLOP   NVARCHAR(100)   NOT NULL,
    MANV     VARCHAR(20)     NULL,

    CONSTRAINT PK_LOP PRIMARY KEY (MALOP),
    CONSTRAINT FK_LOP_NHANVIEN
        FOREIGN KEY (MANV) REFERENCES dbo.NHANVIEN(MANV)
);
GO

CREATE TABLE dbo.HOCPHAN
(
    MAHP     VARCHAR(20)     NOT NULL,
    TENHP    NVARCHAR(100)   NOT NULL,
    SOTC     INT             NULL,

    CONSTRAINT PK_HOCPHAN PRIMARY KEY (MAHP),
    CONSTRAINT CK_HOCPHAN_SOTC CHECK (SOTC IS NULL OR SOTC > 0)
);
GO

CREATE TABLE dbo.SINHVIEN
(
    MASV      VARCHAR(20)      NOT NULL,
    HOTEN     NVARCHAR(100)    NOT NULL,
    NGAYSINH  DATETIME         NULL,
    DIACHI    NVARCHAR(200)    NULL,
    MALOP     VARCHAR(20)      NULL,
    TENDN     NVARCHAR(100)    NOT NULL,
    MATKHAU   VARBINARY(32)    NOT NULL, /* SHA2_256 */

    CONSTRAINT PK_SINHVIEN PRIMARY KEY (MASV),
    CONSTRAINT UQ_SINHVIEN_TENDN UNIQUE (TENDN),
    CONSTRAINT FK_SINHVIEN_LOP
        FOREIGN KEY (MALOP) REFERENCES dbo.LOP(MALOP)
);
GO

CREATE TABLE dbo.BANGDIEM
(
    MASV      VARCHAR(20)      NOT NULL,
    MAHP      VARCHAR(20)      NOT NULL,
    DIEMTHI   VARBINARY(MAX)   NULL,

    CONSTRAINT PK_BANGDIEM PRIMARY KEY (MASV, MAHP),
    CONSTRAINT FK_BANGDIEM_SINHVIEN
        FOREIGN KEY (MASV) REFERENCES dbo.SINHVIEN(MASV),
    CONSTRAINT FK_BANGDIEM_HOCPHAN
        FOREIGN KEY (MAHP) REFERENCES dbo.HOCPHAN(MAHP)
);
GO