USE QLSVNhom;
GO

IF OBJECT_ID(N'dbo.BANGDIEM', N'U') IS NOT NULL DROP TABLE dbo.BANGDIEM;
IF OBJECT_ID(N'dbo.SINHVIEN', N'U') IS NOT NULL DROP TABLE dbo.SINHVIEN;
IF OBJECT_ID(N'dbo.HOCPHAN', N'U') IS NOT NULL DROP TABLE dbo.HOCPHAN;
IF OBJECT_ID(N'dbo.LOP', N'U') IS NOT NULL DROP TABLE dbo.LOP;
IF OBJECT_ID(N'dbo.NHANVIEN', N'U') IS NOT NULL DROP TABLE dbo.NHANVIEN;
GO

-- 1. NHANVIEN
CREATE TABLE dbo.NHANVIEN
(
    MANV     VARCHAR(20)     NOT NULL,
    HOTEN    NVARCHAR(100)   NOT NULL,
    EMAIL    VARCHAR(20)     NULL,
    LUONG    VARBINARY(MAX)  NULL,
    TENDN    NVARCHAR(100)   NOT NULL,
    MATKHAU  VARBINARY(MAX)  NOT NULL,
    PUBKEY   VARCHAR(20)     NULL,

    CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV),
    CONSTRAINT UQ_NHANVIEN_TENDN UNIQUE (TENDN)
);
GO

-- 2. LOP
CREATE TABLE dbo.LOP
(
    MALOP    VARCHAR(20)     NOT NULL,
    TENLOP   NVARCHAR(100)   NOT NULL,
    MANV     VARCHAR(20)     NULL,
    MASV     VARCHAR(20)     NULL, -- Added strictly to match PDF schema string
    MAHP     VARCHAR(20)     NULL, -- Added strictly to match PDF schema string

    CONSTRAINT PK_LOP PRIMARY KEY (MALOP)
);
GO

-- 3. HOCPHAN
CREATE TABLE dbo.HOCPHAN
(
    MAHP     VARCHAR(20)     NOT NULL,
    TENHP    NVARCHAR(100)   NOT NULL,
    SOTC     INT             NULL,

    CONSTRAINT PK_HOCPHAN PRIMARY KEY (MAHP)
);
GO

-- 4. SINHVIEN
CREATE TABLE dbo.SINHVIEN
(
    MASV      NVARCHAR(20)     NOT NULL,
    HOTEN     NVARCHAR(100)    NOT NULL,
    NGAYSINH  DATETIME         NULL,
    DIACHI    NVARCHAR(200)    NULL,
    MALOP     NVARCHAR(200)    NULL,
    TENDN     NVARCHAR(100)    NOT NULL,
    MATKHAU   VARBINARY(MAX)   NOT NULL,

    CONSTRAINT PK_SINHVIEN PRIMARY KEY (MASV),
    CONSTRAINT UQ_SINHVIEN_TENDN UNIQUE (TENDN)
);
GO

-- 5. BANGDIEM
CREATE TABLE dbo.BANGDIEM
(
    MASV      VARCHAR(20)      NOT NULL,
    MAHP      VARCHAR(20)      NOT NULL,
    DIEMTHI   VARBINARY(MAX)   NULL,

    CONSTRAINT PK_BANGDIEM PRIMARY KEY (MASV, MAHP)
);
GO