USE QLSVNhom;
GO

/* 1. INSERT NHANVIEN (Bao gồm VAITRO) */
CREATE OR ALTER PROCEDURE dbo.SP_INS_PUBLIC_ENCRYPT_NHANVIEN
    @MANV       VARCHAR(20),
    @HOTEN      NVARCHAR(100),
    @EMAIL      VARCHAR(100),
    @LUONG      VARCHAR(500),
    @TENDN      NVARCHAR(100),
    @MK         VARCHAR(128),
    @PUB        VARCHAR(500),
    @VAITRO     VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    IF EXISTS (SELECT 1 FROM dbo.NHANVIEN WHERE MANV = @MANV OR TENDN = @MANV)
        THROW 50007, N'MANV đã tồn tại hoặc bị xung đột với TENDN hiện có.', 1;

    DECLARE @MK_BIN VARBINARY(64) = TRY_CONVERT(VARBINARY(64), @MK, 2);

    INSERT INTO dbo.NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU, PUBKEY, VAITRO)
    VALUES (@MANV, @HOTEN, @EMAIL, @LUONG, @TENDN, @MK_BIN, @PUB, @VAITRO);
END
GO

/* 2. SELECT NHANVIEN */
CREATE OR ALTER PROCEDURE dbo.SP_SEL_PUBLIC_ENCRYPT_NHANVIEN
    @TENDN    NVARCHAR(100),
    @MK       VARCHAR(128)
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @MK_BIN VARBINARY(64) = TRY_CONVERT(VARBINARY(64), @MK, 2);

    SELECT TOP (1) MANV, HOTEN, EMAIL, LUONG, VAITRO
    FROM dbo.NHANVIEN
    WHERE (TENDN = @TENDN OR MANV = @TENDN) AND MATKHAU = @MK_BIN;
    
    IF @@ROWCOUNT = 0
        THROW 50013, N'Sai thông tin đăng nhập hoặc không tìm thấy nhân viên.', 1;
END
GO

/* 3. CẬP NHẬT THÔNG TIN NHÂN VIÊN (KHÔNG ĐỔI MẬT KHẨU) */
CREATE OR ALTER PROCEDURE dbo.SP_UPD_NHANVIEN_INFO
    @ACTION_MANV    VARCHAR(20), -- User performing the action
    @TARGET_MANV    VARCHAR(20), -- User being updated
    @NEW_HOTEN      NVARCHAR(100),
    @NEW_EMAIL      VARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;
    
    DECLARE @ROLE VARCHAR(20);
    SELECT @ROLE = VAITRO FROM dbo.NHANVIEN WHERE MANV = @ACTION_MANV;

    IF @ROLE IS NULL
        THROW 50016, N'Người dùng thực hiện không tồn tại.', 1;

    -- Chỉ ADMIN mới được sửa người khác. USER chỉ được sửa chính mình.
    IF @ROLE <> 'ADMIN' AND @ACTION_MANV <> @TARGET_MANV
        THROW 50017, N'Từ chối truy cập: Không có quyền sửa thông tin nhân viên khác.', 1;

    UPDATE dbo.NHANVIEN
    SET HOTEN = @NEW_HOTEN, EMAIL = @NEW_EMAIL
    WHERE MANV = @TARGET_MANV;
END
GO

/* 4. USER TỰ ĐỔI MẬT KHẨU (Yêu cầu mật khẩu cũ để map với Client Pipeline) */
CREATE OR ALTER PROCEDURE dbo.SP_CHANGE_PASSWORD_NHANVIEN
    @MANV           VARCHAR(20),
    @OLD_MK_HASH    VARCHAR(128),
    @NEW_MK_HASH    VARCHAR(128),
    @NEW_PUBKEY     VARCHAR(500),
    @NEW_LUONG      VARCHAR(500)
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @OLD_MK_BIN VARBINARY(64) = TRY_CONVERT(VARBINARY(64), @OLD_MK_HASH, 2);
    DECLARE @NEW_MK_BIN VARBINARY(64) = TRY_CONVERT(VARBINARY(64), @NEW_MK_HASH, 2);

    IF NOT EXISTS (SELECT 1 FROM dbo.NHANVIEN WHERE MANV = @MANV AND MATKHAU = @OLD_MK_BIN)
        THROW 50015, N'Mật khẩu cũ không chính xác.', 1;

    UPDATE dbo.NHANVIEN
    SET MATKHAU = @NEW_MK_BIN,
        PUBKEY = @NEW_PUBKEY,
        LUONG = @NEW_LUONG
    WHERE MANV = @MANV;
END
GO